---
name: mypy

# NOTE: This is a temporary (separate) workflow that runs mypy.
#       We're doing this ahead of its adoption in the main 'test' workflow.

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# (n/a)
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (n/a)

on:
- push

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Run mypy
      run: |
        pip install --upgrade pip
        pip install .[dev]
        mkdir .mypy_cache
        mypy xchemalign
