---
name: test

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# (n/a)
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (n/a)

on:
- push

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - "3.10"
        - "3.11"
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Pre-commit check
      run: |
        pip install --upgrade pip
        pip install .[dev]
        pre-commit run --all-files

  command-help:
    runs-on: ubuntu-latest
    needs:
    - static-analysis
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test command help
      run: |
        pip install --upgrade pip
        pip install .
        python -m xchemalign.copier -h
        python -m xchemalign.collator -h
        python -m xchemalign.aligner -h

  test-data:
    runs-on: ubuntu-latest
    needs:
    - command-help
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test test-data config
      run: |
        pip install --upgrade pip
        pip install .
        mkdir -p test-data/outputs/upload_1
        python -m xchemalign.collator -c test-data/config_1.yaml
        python -m xchemalign.aligner -d test-data/outputs/upload_1
